USE [SRSAnalysis]
GO
/****** Object:  StoredProcedure [dbo].[CreateTableCDATECorrelations4R]    Script Date: 05/16/2014 16:40:22 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
IF NOT EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N'[dbo].[CreateTableCDATECorrelations4R]') AND type in (N'P', N'PC'))
BEGIN
EXEC dbo.sp_executesql @statement = N'-- =============================================
-- Author:		Arthur Wiedmer
-- Create date: 2012-08-24
-- Description:	
-- =============================================
CREATE PROCEDURE [dbo].[CreateTableCDATECorrelations4R] 
	-- Add the parameters for the stored procedure here
AS
BEGIN
	-- SET NOCOUNT ON added to prevent extra result sets from
	-- interfering with SELECT statements.
	SET NOCOUNT ON;

    -- Insert statements for procedure here
		
	if exists (
		select * from sysobjects 
			where id = OBJECT_ID(N''CDATEcorr4R'')
				and OBJECTPROPERTY(id,N''IsUserTable'') = 1
	)
		drop table [SRSAnalysis].[dbo].[CDATEcorr4R]
		
	if exists (
		select * from sysobjects 
			where id = OBJECT_ID(N''CDATEcorrC4R'')
				and OBJECTPROPERTY(id,N''IsUserTable'') = 1
	)
		drop table [SRSAnalysis].[dbo].[CDATEcorrC4R]
		
      
    --create results analysis table (a join with the samples and the stations for XY coords)
    
    /*
    CREATE TABLE corr4R (
    STATION_SEQ	int,
    STATION_ID nvarchar(63),
    EASTING nvarchar(63),
    NORTHING nvarchar(63),
    LATITUDE nvarchar(63),
    LONGITUDE nvarchar(63),
    MDATE smalldatetime,
    MYEAR int,
    MMONTH int,
    MDAY int,
    MQUARTER int,
    ANALYTE_NAME nvarchar(255),
    RESULT float,
    RESULT_UNITS nvarchar(63),
    GROUND_ELEVATION float, 
    REFERENCE_ELEVATION float, 
    TOP_ELEV float, 
    BOTTOM_ELEV float
    )
    
    CREATE TABLE corrC4R (
    STATION_SEQ	int,
    STATION_ID nvarchar(63),
    EASTING nvarchar(63),
    NORTHING nvarchar(63),
    LATITUDE nvarchar(63),
    LONGITUDE nvarchar(63),
    MDATE smalldatetime,
    MYEAR int,
    MMONTH int,
    MDAY int,
    MQUARTER int,
    ANALYTE_NAME nvarchar(255),
    RESULT float,
    RESULT_UNITS nvarchar(63),
    GROUND_ELEVATION float, 
    REFERENCE_ELEVATION float, 
    TOP_ELEV float, 
    BOTTOM_ELEV float
    )
    */
    
    --Create correlations table
    
    SELECT [STATION_SEQ]
      ,[STATION_ID]
      ,[EASTING]
      ,[NORTHING]
      ,[LATITUDE]
      ,[LONGITUDE]
      ,[GROUND_ELEVATION]
      ,[REFERENCE_ELEVATION]
      ,[TOP_ELEV]
      ,[BOTTOM_ELEV]
      ,[CDATE]
      ,[TRITIUM],[NONVOLATILE BETA],[GROSS ALPHA],[CADMIUM],[LEAD],[NITRATE-NITRITE AS NITROGEN],[ALUMINUM],[PH],[SPECIFIC CONDUCTANCE],[MERCURY],[SILVER],[BARIUM],[CHROMIUM],[ZINC],[ARSENIC],[SELENIUM],[NICKEL],[COPPER],[COBALT],[THALLIUM],[ANTIMONY],[VANADIUM],[CYANIDE],[IRON],[RADIUM-226],[IODINE-129],[RADIUM-228],[URANIUM-235],[URANIUM-238],[CESIUM-137],[URANIUM-233/234],[COBALT-60],[TECHNETIUM-99],[RADIUM, TOTAL ALPHA-EMITTING],[BERYLLIUM],[STRONTIUM-90],[AMERICIUM-241],[CHLORIDE],[THORIUM-228],[THORIUM-232],[CURIUM-243/244],[THORIUM-230],[CURIUM-242],[MANGANESE],[PLUTONIUM-238],[PLUTONIUM-239/240],[SODIUM],[CURIUM-245/246],[MAGNESIUM],[POTASSIUM],[CALCIUM],[TOTAL ACTIVITY],[CARBON-14],[CESIUM-134],[TOTAL ORGANIC CARBON],[POTASSIUM-40],[SULFATE],[ANTIMONY-125],[TOTAL PHOSPHATES (AS  P)],[EUROPIUM-154],[EUROPIUM-155],[PROMETHIUM-146],[EUROPIUM-152],[FLUORIDE],[TOTAL DISSOLVED SOLIDS],[ACTINIUM-228],[LEAD-212],[TIN],[RUTHENIUM-106],[CERIUM-144],[NITRATE],[MANGANESE-54],[ZINC-65],[SODIUM-22],[COBALT-57],[PROMETHIUM-144],[YTTRIUM-88],[BARIUM-133],[URANIUM],[NEPTUNIUM-237],[ZIRCONIUM-95],[STRONTIUM-89],[STRONTIUM],[STRONTIUM-89/90],[AMERICIUM-243]
    into CDATEcorr4R
    FROM 
    (select [STATION_SEQ]
      ,[STATION_ID]
      ,[EASTING]
      ,[NORTHING]
      ,[LATITUDE]
      ,[LONGITUDE]
      ,[GROUND_ELEVATION]
      ,[REFERENCE_ELEVATION]
      ,[TOP_ELEV]
      ,[BOTTOM_ELEV]
      ,[COLLECTION_DATE] as CDATE
      ,[ANALYTE_NAME]
      ,CONVERT(float,[RESULT]) as [RESULT]
      from [SRSAnalysis].[dbo].[results4R]) p
    PIVOT
    (
    AVG(RESULT)
    FOR ANALYTE_NAME in ([TRITIUM],[NONVOLATILE BETA],[GROSS ALPHA],[CADMIUM],[LEAD],[NITRATE-NITRITE AS NITROGEN],[ALUMINUM],[PH],[SPECIFIC CONDUCTANCE],[MERCURY],[SILVER],[BARIUM],[CHROMIUM],[ZINC],[ARSENIC],[SELENIUM],[NICKEL],[COPPER],[COBALT],[THALLIUM],[ANTIMONY],[VANADIUM],[CYANIDE],[IRON],[RADIUM-226],[IODINE-129],[RADIUM-228],[URANIUM-235],[URANIUM-238],[CESIUM-137],[URANIUM-233/234],[COBALT-60],[TECHNETIUM-99],[RADIUM, TOTAL ALPHA-EMITTING],[BERYLLIUM],[STRONTIUM-90],[AMERICIUM-241],[CHLORIDE],[THORIUM-228],[THORIUM-232],[CURIUM-243/244],[THORIUM-230],[CURIUM-242],[MANGANESE],[PLUTONIUM-238],[PLUTONIUM-239/240],[SODIUM],[CURIUM-245/246],[MAGNESIUM],[POTASSIUM],[CALCIUM],[TOTAL ACTIVITY],[CARBON-14],[CESIUM-134],[TOTAL ORGANIC CARBON],[POTASSIUM-40],[SULFATE],[ANTIMONY-125],[TOTAL PHOSPHATES (AS  P)],[EUROPIUM-154],[EUROPIUM-155],[PROMETHIUM-146],[EUROPIUM-152],[FLUORIDE],[TOTAL DISSOLVED SOLIDS],[ACTINIUM-228],[LEAD-212],[TIN],[RUTHENIUM-106],[CERIUM-144],[NITRATE],[MANGANESE-54],[ZINC-65],[SODIUM-22],[COBALT-57],[PROMETHIUM-144],[YTTRIUM-88],[BARIUM-133],[URANIUM],[NEPTUNIUM-237],[ZIRCONIUM-95],[STRONTIUM-89],[STRONTIUM],[STRONTIUM-89/90],[AMERICIUM-243])
    ) as pvt
    order by STATION_SEQ, CDATE
    
    --Aquifer C
    
    SELECT [STATION_SEQ]
      ,[STATION_ID]
      ,[EASTING]
      ,[NORTHING]
      ,[LATITUDE]
      ,[LONGITUDE]
      ,[GROUND_ELEVATION]
      ,[REFERENCE_ELEVATION]
      ,[TOP_ELEV]
      ,[BOTTOM_ELEV]
      ,[CDATE]
      ,[TRITIUM],[NONVOLATILE BETA],[GROSS ALPHA],[CADMIUM],[LEAD],[NITRATE-NITRITE AS NITROGEN],[ALUMINUM],[PH],[SPECIFIC CONDUCTANCE],[MERCURY],[SILVER],[BARIUM],[CHROMIUM],[ZINC],[ARSENIC],[SELENIUM],[NICKEL],[COPPER],[COBALT],[THALLIUM],[ANTIMONY],[VANADIUM],[CYANIDE],[IRON],[RADIUM-226],[IODINE-129],[RADIUM-228],[URANIUM-235],[URANIUM-238],[CESIUM-137],[URANIUM-233/234],[COBALT-60],[TECHNETIUM-99],[RADIUM, TOTAL ALPHA-EMITTING],[BERYLLIUM],[STRONTIUM-90],[AMERICIUM-241],[CHLORIDE],[THORIUM-228],[THORIUM-232],[CURIUM-243/244],[THORIUM-230],[CURIUM-242],[MANGANESE],[PLUTONIUM-238],[PLUTONIUM-239/240],[SODIUM],[CURIUM-245/246],[MAGNESIUM],[POTASSIUM],[CALCIUM],[TOTAL ACTIVITY],[CARBON-14],[CESIUM-134],[TOTAL ORGANIC CARBON],[POTASSIUM-40],[SULFATE],[ANTIMONY-125],[TOTAL PHOSPHATES (AS  P)],[EUROPIUM-154],[EUROPIUM-155],[PROMETHIUM-146],[EUROPIUM-152],[FLUORIDE],[TOTAL DISSOLVED SOLIDS],[ACTINIUM-228],[LEAD-212],[TIN],[RUTHENIUM-106],[CERIUM-144],[NITRATE],[MANGANESE-54],[ZINC-65],[SODIUM-22],[COBALT-57],[PROMETHIUM-144],[YTTRIUM-88],[BARIUM-133],[URANIUM],[NEPTUNIUM-237],[ZIRCONIUM-95],[STRONTIUM-89],[STRONTIUM],[STRONTIUM-89/90],[AMERICIUM-243]
    into CDATEcorrC4R
    FROM 
    (select [STATION_SEQ]
      ,[STATION_ID]
      ,[EASTING]
      ,[NORTHING]
      ,[LATITUDE]
      ,[LONGITUDE]
      ,[GROUND_ELEVATION]
      ,[REFERENCE_ELEVATION]
      ,[TOP_ELEV]
      ,[BOTTOM_ELEV]
      ,[COLLECTION_DATE] as CDATE
      ,[ANALYTE_NAME]
      ,CONVERT(float,[RESULT]) as [RESULT]
      from [SRSAnalysis].[dbo].[resultsC4R]) p
    PIVOT
    (
    AVG(RESULT)
    FOR ANALYTE_NAME in ([TRITIUM],[NONVOLATILE BETA],[GROSS ALPHA],[CADMIUM],[LEAD],[NITRATE-NITRITE AS NITROGEN],[ALUMINUM],[PH],[SPECIFIC CONDUCTANCE],[MERCURY],[SILVER],[BARIUM],[CHROMIUM],[ZINC],[ARSENIC],[SELENIUM],[NICKEL],[COPPER],[COBALT],[THALLIUM],[ANTIMONY],[VANADIUM],[CYANIDE],[IRON],[RADIUM-226],[IODINE-129],[RADIUM-228],[URANIUM-235],[URANIUM-238],[CESIUM-137],[URANIUM-233/234],[COBALT-60],[TECHNETIUM-99],[RADIUM, TOTAL ALPHA-EMITTING],[BERYLLIUM],[STRONTIUM-90],[AMERICIUM-241],[CHLORIDE],[THORIUM-228],[THORIUM-232],[CURIUM-243/244],[THORIUM-230],[CURIUM-242],[MANGANESE],[PLUTONIUM-238],[PLUTONIUM-239/240],[SODIUM],[CURIUM-245/246],[MAGNESIUM],[POTASSIUM],[CALCIUM],[TOTAL ACTIVITY],[CARBON-14],[CESIUM-134],[TOTAL ORGANIC CARBON],[POTASSIUM-40],[SULFATE],[ANTIMONY-125],[TOTAL PHOSPHATES (AS  P)],[EUROPIUM-154],[EUROPIUM-155],[PROMETHIUM-146],[EUROPIUM-152],[FLUORIDE],[TOTAL DISSOLVED SOLIDS],[ACTINIUM-228],[LEAD-212],[TIN],[RUTHENIUM-106],[CERIUM-144],[NITRATE],[MANGANESE-54],[ZINC-65],[SODIUM-22],[COBALT-57],[PROMETHIUM-144],[YTTRIUM-88],[BARIUM-133],[URANIUM],[NEPTUNIUM-237],[ZIRCONIUM-95],[STRONTIUM-89],[STRONTIUM],[STRONTIUM-89/90],[AMERICIUM-243])
    ) as pvt
    order by STATION_SEQ, CDATE
    
    
    --
    
  
	
	--
	
	
/*
IODINE-129
CESIUM-137
TECHNETIUM-99
COBALT-60
STRONTIUM-90
AMERICIUM-241
PLUTONIUM-238
PLUTONIUM-239/240
THORIUM-228
CURIUM-243/244
THORIUM-232
CURIUM-242
THORIUM-230
CURIUM-245/246
TOTAL ACTIVITY
CESIUM-134
POTASSIUM-40
ANTIMONY-125
ACTINIUM-228
RUTHENIUM-106
*/
		
END
' 
END
GO
